### ISSUE TITLE
[BUG] archetype documentation and behavior are inconsistent

### ISSUE THREAD

**Issue by xtnh** [IKOR-GmbH/sip-framework#238]
**Description**
Using the archetype to get started as described in the documentation (specifying archetypeGroupId, archetypeArtifactId, archetypeVersion, groupId, artifactId, projectName, version) results in a build error indicating that the connectorGroup1, connectorGroup2 and packageSuffix properties are missing.
The documentation says _"After executing given Maven command, you will be requested to insert additional parameters about project structure:"_ so one might expect the archetype Maven build to build successfully.
This is inconsistent behaviour of the archetype towards the documentation.

**Reproduction**
Execute the following command:
mvn archetype:generate -DarchetypeGroupId=de.ikor.sip.foundation -DarchetypeArtifactId=sip-archetype -DarchetypeVersion=3.2.0 -DgroupId=foo -DartifactId=foo -DprojectName=foo -Dversion=1.0.0-SNAPSHOT

**Expected behavior**
"BUILD SUCCESS" as result of the maven build.

**SIP (please complete the following information):**
 - Involved components: archetype, docs
 - Version: 3.2.0

**Screenshot**
![image](https://github.com/IKOR-GmbH/sip-framework/assets/1881914/e5667fed-157c-425d-a8be-d3631a0c9ff6)

**Comment by LetoBukarica** [comment]
@xtnh Hi, can you try deleting ~/.m2/repository/de/ikor/sip/foundation/sip-archetype/ (and ~/.m2/repository/archetype-catalog.xml) files and running it again?

We encountered issues with maven-archetype-plugin and multiple archetype versions.

It looks like this for me (with Apache Maven 3.8.4 and Java 17.0.5):
![image](https://github.com/IKOR-GmbH/sip-framework/assets/17590248/e6c36a07-abd2-400d-b5f0-58eddaef575b)

**Comment by xtnh** [comment]
Deleting folder and xml file did not help. A colleague was able to reproduce the behavior.

**Comment by LetoBukarica** [comment]
Can you add more details about the execution environment? Which OS, version of Java, Maven, ... ? It seems that an archetype catalog is redacted on your screenshot. I would suspect an older version of the archetype is cached somewhere which doesn't work with the new version of the framework. We would first need to reproduce the issue, that's why I'm asking for the execution environment.
Thanks

**Comment by xtnh** [comment]
OS: Windows 10 Enterprise, Version 21H2, OS Build 19044.3570
Java: Eclipse Adoptium jdk-17.0.6.10-hotspot
Maven: 3.8.5

These are details for my work computer, where I have tried everything. I have not come to test everything on my home computer. I will hopefully do that in the next few days.

**Comment by Hauke-Schroeder** [comment]
@LetoBukarica 

I encountered following things:
- no default values for connector groups; only non-capital letters are accepted as connector groups but the hint indicates a capital case letter is okay (see the attached log)
- package suffix is enforced to be set (none is the chosen string literal)

I was not able to proceed without setting the parameters, so for me the initial problem was not reproducable.


System information:
`
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Java version: 17, vendor: Azul Systems, Inc.
`

`mvn archetype:generate -DarchetypeGroupId=de.ikor.sip.foundation -DarchetypeArtifactId=sip-archetype -DarchetypeVersion=3.2.0 -DgroupId=foo -DartifactId=foo -DprojectName=foo -Dversion=1.0.0-SNAPSHOT
[INFO] Scanning for projects...
Downloading from 

[...]

[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> archetype:3.2.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< archetype:3.2.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- archetype:3.2.1:generate (default-cli) @ standalone-pom ---

[...]

[INFO] Using property: groupId = foo
[INFO] Using property: version = 1.0.0-SNAPSHOT
Define value for property 'connectorGroup1' (should match expression '^[a-z][a-z0-9]*$'):
Value does not match the expression, please try again: connectorGroup1
Value does not match the expression, please try again: connectorgroup1
Define value for property 'connectorGroup2' (should match expression '^[a-z][a-z0-9]*$'): connectorgroup2
Define value for property 'packageSuffix' (should match expression '^[a-z][a-z0-9]*$'):
Value does not match the expression, please try again: none
[INFO] Using property: useLombokDefault = y
[INFO] Using property: useSoapDefault = n
[INFO] Using property: archetypeVersion = 3.2.0
[INFO] Using property: artifactId = foo
[INFO] Using property: projectName = foo
Define value for property 'useLombok' y: : n
Define value for property 'useSoap' n: : n
Define value for property 'package' (should match expression '^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9]*)*$') foo.none: : bla
Confirm properties configuration:
groupId: foo
version: 1.0.0-SNAPSHOT
connectorGroup1: connectorgroup1
connectorGroup2: connectorgroup2
packageSuffix: none
useLombokDefault: y
useSoapDefault: n
archetypeVersion: 3.2.0
artifactId: foo
projectName: foo
useLombok: n
useSoap: n
package: bla
 Y: : y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: sip-archetype:3.2.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: foo
[INFO] Parameter: artifactId, Value: foo
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: package, Value: bla
[INFO] Parameter: packageInPathFormat, Value: bla
[INFO] Parameter: package, Value: bla
[INFO] Parameter: useSoapDefault, Value: n
[INFO] Parameter: groupId, Value: foo
[INFO] Parameter: connectorGroup1, Value: connectorgroup1
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: packageSuffix, Value: none
[INFO] Parameter: archetypeVersion, Value: 3.2.0
[INFO] Parameter: connectorGroup2, Value: connectorgroup2
[INFO] Parameter: useLombok, Value: n
[INFO] Parameter: artifactId, Value: foo
[INFO] Parameter: useLombokDefault, Value: y
[INFO] Parameter: projectName, Value: foo
[INFO] Parameter: useSoap, Value: n
[INFO] Project created from Archetype in dir: C:\Workspace\test\foo
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:41 min
[INFO] Finished at: 2023-11-03T19:38:01+01:00
[INFO] ------------------------------------------------------------------------`

**Comment by xtnh** [comment]
Test on my private home computer was successful.
Setup:
> Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
> Java version: 17.0.3, vendor: Eclipse Adoptium, 
> OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

Beside that the documentation is still inconsistent IMHO.

**Comment by LetoBukarica** [comment]
I'm changing the tag to mark it as a documentation issue. We'll be updating the docs in the next release. @xtnh @HaukeSchroederIkor thank you for your input, greatly appreciated.
